# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Fitmoji' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapSDK'

  # Pods for Fitmoji

  target 'FitmojiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitmojiUITests' do
    # Pods for testing
  end

end
